-- Grab average load times for specific packages in Oracle metadata log
SELECT OBJECT_NAME,numtodsinterval( 
 AVG(EXTRACT( day from RUN_TIME )*24*60*60+ 
 EXTRACT( hour from RUN_TIME )*60*60+ 
 EXTRACT( minute from RUN_TIME )*60+ 
 EXTRACT( second from RUN_TIME)), 'second') AVG_RUN 
FROM STG_FMS90.ETL_META_OBJ_LOG
WHERE OBJECT_NAME IN ('STG_HCM_MAXEFFDT_XLAT','STG_HCM_PRE_COMP','STG_HCM_PRE_PER_ORG','STG_HCM_MAXEFFDT_ACTION'
,'STG_HCM_MAXEFFDT_ACTRSN','STG_HCM_MAXEFFDT_POSITION','STG_HCM_FACT_JOB','STG_HCM_DIM_JOB','STG_HCM_DIM_POSITION','DIM_HCM_POSITION')
AND ETL_PROCESS_DATE > '01-JAN-2016' /* timeframe selection */
and status = 'SUCCESS'
GROUP BY OBJECT_NAME
ORDER BY OBJECT_NAME desc
;